pipeline:
  docker:
    image: plugins/docker
    repo: iteam1337/rancher-caddy
    username: ${DOCKER_USER}
    password: ${DOCKER_PASS}
    email: src@ilix.se
    tags: latest
  rancher:
    image: peloton/drone-rancher
    url: http://5.35.191.41:8080
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: Infra/infra
    docker_image: iteam1337/rancher-caddy:latest
    start_first: false
    confirm: true
